### ISSUE TITLE
something with mappoing

### ISSUE THREAD

**Issue by lonix** [linuxserver/docker-kodi-headless#1]
Someone emailed me this.

It looks like you guys are writing to /config/.kodi in the docker but from /mnt/user/.appdata/kodi(where I keep my cfg files)/.kodi (created because of the way the docker is configured) I don't ever see any files outside of the docker (/mnt/user/.appdata/kodi/.kodi).  It's just empty.  Maybe because it's not top-level? 

Anyway, I changed the mapping to /config/.kodi (docker) <-> /mnt/cache/.appdata/kodi and I can see the files now from outside docker exec now.  Before it created the /mnt/cache/.appdata/kodi/.kodi structure but it was empty but the exec session was full of folders/files in /config/.kodi.  And yes, I ll'd (ls -al).  The /mnt/cache/appdata/kodi/.kodi folder was really empty.

**Comment by sparklyballs** [comment]
won't see the files in /mnt/user/.appdata/kodi/.kodi outside of the docker because by default .files and .folders are hidden.
