### ISSUE TITLE
Traefik as reverse proxy

### ISSUE THREAD

**Issue by gurabli** [linuxserver/docker-kodi-headless#100]
Running docker fine and I use Traefik as reverse proxy. I can access Chorus2 on kodi.domain.com fine.
However, I can't make Sonarr to connect to kodi.domain.com.

Does anyone use Traefik as proxy? If yes, what is the configuration? I have the following:

```
    labels:
      - "traefik.enable=true"
      - "traefik.backend=kodi"
      - "traefik.frontend.rule=Host:kodi.${DOMAINNAME}"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
```

**Comment by jsaddiction** [comment]
As long as they are both on the same network you can just set the host portion in your connect settings in sonarr to your kodi service name. In my case I have it set to "kodi-headless"

**Comment by jsaddiction** [comment]
since we are on the subject of reverse proxy, I am struggling to get websockets functioning correctly with this container.  Typically websockets are established over port 9090.  for whatever reason i always get "err connection refused" Got any suggestions?
