### ISSUE TITLE
RPi 4 with Raspbian Buster support

### ISSUE THREAD

**Issue by theboxer** [linuxserver/docker-kodi-headless#103]
Is there a way how to make the headless kodi docker image run on Raspberry Pi 4 running a Raspbian Buster? I tried cloning the repo and building the image on my own, but no luck. Ended up with:
```
make: *** [all] Error 2
Makefile:140: recipe for target 'all' failed
The command '/bin/sh -c cd /tmp/kodi-source/build &&  cmake ../.        -DCMAKE_INSTALL_LIBDIR=/usr/lib         -DCMAKE_INSTALL_PREFIX=/usr     -DENABLE_AIRTUNES=OFF   -DENABLE_ALSA=OFF       -DENABLE_AVAHI=OFF      -DENABLE_BLUETOOTH=OFF  -DENABLE_BLURAY=ON    -DENABLE_CAP=OFF         -DENABLE_CEC=OFF        -DENABLE_DBUS=OFF       -DENABLE_DVDCSS=OFF     -DENABLE_GLX=OFF        -DENABLE_INTERNAL_FLATBUFFERS=ON        -DENABLE_LIBUSB=OFF     -DENABLE_NFS=ON         -DENABLE_OPENGL=OFF     -DENABLE_OPTICAL=OFF    -DENABLE_PULSEAUDIO=OFF        -DENABLE_SNDIO=OFF      -DENABLE_UDEV=OFF       -DENABLE_UPNP=ON        -DENABLE_VAAPI=OFF      -DENABLE_VDPAU=OFF &&  make -j3 &&  make DESTDIR=/tmp/kodi-build install' returned a non-zero code: 2
```

**Comment by aptalca** [comment]
Use image `lsioarmhf/kodi-headless` instead of `linuxserver/kodi-headless`

**Comment by aptalca** [comment]
Or you can build the arm version with `docker build -f Dockerfile.armhf -t imagename .`

**Comment by Rathna-K** [comment]
> Use image `lsioarmhf/kodi-headless` instead of `linuxserver/kodi-headless`

I see a docker hub link for it but is it opensource ,do you have a github link to this? if not I think we should build ourselves rather than trust an unknown source correct?

**Comment by aptalca** [comment]
It's the same repo, it's just that the arm dockerfile used to push to the lsioarmhf endpoint before we switched most images to multi-arch. We no longer need/use it for the other images

**Comment by Rathna-K** [comment]
thank you, do we still need to use lsioarmhf endpoint? I dont see any arm tags in the kodi-headless.

**Comment by mnovait** [comment]
> Or you can build the arm version locally with `docker build -f Dockerfile.armhf -t imagename .`

for what is worth, I had the same issue and it worked for me
