### ISSUE TITLE
Bump Kodi Leia to 18.5?

### ISSUE THREAD

**Issue by matthuisman** [linuxserver/docker-kodi-headless#105]
Hi @sparklyballs
Would you be able to please bump Leia up-to version 18.5?

**Comment by aptalca** [comment]
@matthuisman just fyi, this project currently has no maintainer. The team is evaluating options moving forward. I don't think there will be any updates until we figure out the path forward, and ultimately it may get deprecated.

**Comment by matthuisman** [comment]
Thanks for the info.
I'll just fork it I guess :)

**Comment by CHBMB** [comment]
@matthuisman If you're going to do that, any reason why you wouldn't take it on as maintainer so everyone could benefit?

**Comment by matthuisman** [comment]
I don't want to commit to that at the moment.

So, I'll just do my "own" so there is no commitment to maintaining it.
https://hub.docker.com/repository/docker/matthuisman/kodi-headless
It's currently building 18.5. Should be up within next few hours.

**Comment by CHBMB** [comment]
That's a shame.  Not that I use this myself though.
