### ISSUE TITLE
kodi settings files not written in docker volume at /config/.kodi

### ISSUE THREAD

**Issue by nicxvan** [linuxserver/docker-kodi-headless#106]
I have the config mapped to a volume, if I ssh into the server I can see the files in /config/.kodi, but they are not in the host system's volume.

Here is my docker-compose:

```
kodi:
    image: linuxserver/kodi-headless
    restart: unless-stopped
    container_name: kodi
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/docker/kodi:/config
      - /mnt/video:/media/video
      - /mnt/music:/media/music
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - 7888:8080
      - 9090:9090
      - 9777:9777/udp```

**Comment by CHBMB** [comment]
Where is `/srv/docker/kodi` 

Is it a local file system?  Not a mounted drive?

**Comment by nicxvan** [comment]
It is the local file system for the docker host.

**Comment by BrianMoos** [comment]
change your volume `- /srv/docker/kodi:/config` to `- /srv/docker/kodi:/config/.kodi` and it'll work.

**Comment by objque** [comment]
same problem for me. i just tried to allow unknown sources, but settings doesn't save. i tried set gid/uid to 0 (root), remove mounted volume and that didn't work for me

I try to run docker container from the latest image on my remote ubuntu server without any gui. 
I suggested that i may use web ui for streaming films
