### ISSUE TITLE
Can't connect to external MySQL database

### ISSUE THREAD

**Issue by mrwolf78** [linuxserver/docker-kodi-headless#113]
On my RPI I have the kodi-headless docker running, but I can't get it to connect to the mysql-database on my Synology NAS.

In my advancedsettings.xml the following is added:

```
<videodatabase>
<type>mysql</type> <!-- don't change this value -->  
<host>192.168.0.15</host> <!-- change this to the IP address of your mysql/mariadb server  -->
<port>3306</port> <!-- change this to the port of your mysql/mariadb server  -->
<user>xmbc</user> <!-- change this to the user for your database, not root  --> 
<pass>****</pass> <!-- change this to the password for your database -->
</videodatabase>
```

This config is working fine on the Kodi instances on my Windows 10-machine and nvidia Shield, so it's correct and working.

Kodi log acknowledges the loading of this xml-file without errors, but for some reason tries to connect to a different IP-address:

`2020-04-14 15:11:19.815 T:1887847280   ERROR: Unable to open database: MyVideos116 [1045](Access denied for user 'xmbc'@'192.168.0.86' (using password: YES))`

192.168.0.86 is the local IP-address of the RPI, which is not configured anywhere. What am I missing here?

**Comment by hugepants** [comment]
Check your username and password. Is `xmbc` a typo for `xbmc`?

The `Access denied` log entry is correctly reporting the IP address of the requesting client.

**Comment by mrwolf78** [comment]
The number of cursewords that just escaped my mouth are too many... I've been looking at this issue for over 2 days, and tried numerous things..

It was a frigging typo...
