### ISSUE TITLE
in the arm/ pi version getting permission denied for samba shares. 

### ISSUE THREAD

**Issue by Rathna-K** [linuxserver/docker-kodi-headless#114]
I have installed the image from lsioarmhf/kodi-headless:latest and i am able to view the movies from myql database and posters etc. loads ok. but I am having issue scanning for library even for one movie.  when I refresh a movie for example i am getting permission denied for the samba share. the same share works when I map using mount.cifs in host. is this a limitation with this image or am i doing something wrong? 
`
sources.xml: 
    <video>
        <default pathversion="1"></default>
        <source>
            <name>Movies</name>
            <path pathversion="1">smb://username:password@my-local-lan-ip/share/</path>
            <allowsharing>true</allowsharing>
        </source>
    </video>
`
error in Kodi log when I  tail -f /.kodi/temp/kodi.log
`
2020-04-24 14:45:36.093 T:2962637680   ERROR: SMBDirectory->GetDirectory: Unable to open directory : 'smb://my-ip/share/movie-name'
                                            unix_err:'d' error : 'Permission denied'
2020-04-24 14:45:36.093 T:2962637680   ERROR: GetDirectory - Error getting smb://my-ip/share/movie-name/
`

**Comment by Rathna-K** [comment]
@aptalca any chance of help? Thanks in Advance

**Comment by hugepants** [comment]
> is this a limitation with this image or am i doing something wrong?

There are no known limitations with the Samba client in kodi-headless so it's likely an issue with your configuration.

> when I refresh a movie for example i am getting permission denied for the samba share

What command are you sending to kodi-headless to refresh? 

Can you provide more information about your set up?

On what device was the initial scan performed and what is its movie `<source>`?

What are the values of `my-local-lan-ip` and `my-ip`?

Create a `../userdata/passwords.xml` for kodi-headless with the following contents:

```
<passwords>
    <path>
        <from pathversion="1">smb://ip-of-samba-server/</from>
        <to pathversion="1">smb://username:password@ip-of-samba-server/</to>
    </path>
</passwords>
```

**Comment by Rathna-K** [comment]
Thank you after adding the password in a separate xml file it worked. Looks like the username passwords inside is not sources.xml file. I highly appreciate your help, thank you 🙏🏻
