### ISSUE TITLE
libnfs missing

### ISSUE THREAD

**Issue by brutaldev** [linuxserver/docker-kodi-headless#26]
If the headless Kodi instance tries to connect to any NFS shares then you see the following error in the log:

```
ERROR: Unable to load libnfs.so.8, reason: Error loading shared library libnfs.so.8: No such file or directory
ERROR: NFS: Error loading libnfs (HandleDyLoad).
```

Access to NFS shares subsequently fail:

`WARNING: Process directory 'nfs://192.168.1.1/folder/etc' does not exist - skipping scan.`

I tried updating the container by installing libnfs (`apk add libnfs`) and verified that libnfs.so.8 exists in /usr/lib but the error still persists.

**Comment by Kolbasz12** [comment]
I was able to to run apk add --no-cache libnfs and it worked

It was a clean image, deleted config and downloaded fresh when I did it

**Comment by brutaldev** [comment]
The new build (17th September) after this fix just goes on a restart cycle so I can't even test if the fix works. The log file keeps getting overwritten so not sure why it crashes  but it just endlessly restarts over and over... Any suggestions on how to debug this?

**Comment by sparklyballs** [comment]
see #25

**Comment by brutaldev** [comment]
@sparklyballs Thanks, I don't see segfaults like in that issue but that could very well be the problem. Subscribed to be notified when it's fixed up.
