### ISSUE TITLE
Docker starts, kodi does not. Please advise (kodi.bin[29199]: segfault at 7a8 ip 00007f9616d90277 sp 00007f9600288750 error 4 in kodi.bin[7f9616614000+201c000])

### ISSUE THREAD

**Issue by simkin** [linuxserver/docker-kodi-headless#41]
I am new to working with docker so it is likely that I am making mistakes but I do not see it. My host is a Debian Jessie server and I pulled image "linuxserver/kodi-headless:Jarvis" to play with. 

root@nas:~/.kodi# uname -a
> Linux nas 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux

docker-engine version = 1.12.3-0~jessie

I have created a new container 
> docker create --name=lucas-test -v /root/.kodi:/config/.kodi -p 7080:7080 -p 7777:9777/udp linuxserver/kodi-headless:Jarvis

and started it:
![image](https://cloud.githubusercontent.com/assets/958263/20755291/b542cc56-b70e-11e6-815a-a725c4db4ef2.png)

root@nas:~/.kodi# docker logs lucas-test
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 10-adduser: executing...
> 
> -------------------------------------
>           _     _ _
>          | |___| (_) ___
>          | / __| | |/ _ \
>          | \__ \ | | (_) |
>          |_|___/ |_|\___/
>                |_|
> 
> Brought to you by linuxserver.io
> We gratefully accept donations at:
> https://www.linuxserver.io/index.php/donations/
> -------------------------------------
> GID/UID
> -------------------------------------
> User uid:    911
> User gid:    911
> -------------------------------------
> 
> [cont-init.d] 10-adduser: exited 0.
> [cont-init.d] 30-config: executing...
> [cont-init.d] 30-config: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> 

But I noticed that I could not connect to the forwarded port and after connecting to the container it looks to me kodi is not running that well. I was able to connect to the DB from within the container. Please advise what is going wrong and if this is likely me messing up or something else :)

docker exec -it lucas-test /bin/bash
root@c34e43bb6fd3:/$ dmesg
> [444036.891874] IPv6: ADDRCONF(NETDEV_CHANGE): veth7e43381: link becomes ready
> [444036.891895] docker0: port 1(veth7e43381) entered forwarding state
> [444036.891902] docker0: port 1(veth7e43381) entered forwarding state
> [444051.940593] docker0: port 1(veth7e43381) entered forwarding state
> [444055.626402] kodi.bin[21875]: segfault at 7a8 ip 00007fdccdf44277 sp 00007fdcb743c750 error 4 in kodi.bin[7fdccd7c8000+201c000]
> [444074.217216] kodi.bin[21997]: segfault at 7a8 ip 00007f66d2791277 sp 00007f66bbc89750 error 4 in kodi.bin[7f66d2015000+201c000]
> [444092.894624] kodi.bin[22165]: segfault at 7a8 ip 00007f1ae1479277 sp 00007f1aca971750 error 4 in kodi.bin[7f1ae0cfd000+201c000]
> [444111.593276] kodi.bin[22286]: segfault at 7a8 ip 00007f12200bf277 sp 00007f12095b7750 error 4 in kodi.bin[7f121f943000+201c000]
> [444130.367787] kodi.bin[22401]: segfault at 7a8 ip 00007f66c12a1277 sp 00007f66aa799750 error 4 in kodi.bin[7f66c0b25000+201c000]
> [444144.976039] docker0: port 1(veth7e43381) entered disabled state
> [444145.047436] docker0: port 1(veth7e43381) entered disabled state
> [444145.047964] device veth7e43381 left promiscuous mode
> [444145.047972] docker0: port 1(veth7e43381) entered disabled state
> [444145.256677] device vetha5cf1a5 entered promiscuous mode
> [444145.256722] IPv6: ADDRCONF(NETDEV_UP): vetha5cf1a5: link is not ready
> [444145.256726] docker0: port 1(vetha5cf1a5) entered forwarding state
> [444145.256730] docker0: port 1(vetha5cf1a5) entered forwarding state
> [444145.440348] docker0: port 1(vetha5cf1a5) entered disabled state
> [444145.440921] device vetha5cf1a5 left promiscuous mode
> [444145.440928] docker0: port 1(vetha5cf1a5) entered disabled state
> [444180.849413] aufs au_opts_verify:1570:dockerd[18312]: dirperm1 breaks the protection by the permission bits on the lower branch
> [444180.872692] device veth7f7c98f entered promiscuous mode
> [444180.872734] IPv6: ADDRCONF(NETDEV_UP): veth7f7c98f: link is not ready
> [444180.872737] docker0: port 1(veth7f7c98f) entered forwarding state
> [444180.872742] docker0: port 1(veth7f7c98f) entered forwarding state
> [444180.873268] docker0: port 1(veth7f7c98f) entered disabled state
> [444181.028496] docker0: port 1(veth7f7c98f) entered disabled state
> [444181.028951] device veth7f7c98f left promiscuous mode
> [444181.028956] docker0: port 1(veth7f7c98f) entered disabled state
> [444197.923751] Firewall: *TCP_OUT Blocked* IN= OUT=br0 SRC=192.168.0.240 DST=192.168.0.28 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=59786 DF PROTO=TCP SPT=44463 DPT=9090 WINDOW=29200 RES=0x00 SYN URGP=0 UID=0 GID=0
> [444199.053803] Firewall: *UDP_IN Blocked* IN=br0 OUT= PHYSIN=eth0 MAC=d0:50:99:09:98:ae:00:17:88:28:ae:f5:08:00 SRC=192.168.0.94 DST=192.168.0.240 LEN=324 TOS=0x00 PREC=0x00 TTL=64 ID=50424 DF PROTO=UDP SPT=1900 DPT=33570 LEN=304
> [444323.225217] aufs au_opts_verify:1570:dockerd[1673]: dirperm1 breaks the protection by the permission bits on the lower branch
> [444323.291825] device veth4342849 entered promiscuous mode
> [444323.291862] IPv6: ADDRCONF(NETDEV_UP): veth4342849: link is not ready
> [444323.291865] docker0: port 1(veth4342849) entered forwarding state
> [444323.291870] docker0: port 1(veth4342849) entered forwarding state
> [444323.293272] docker0: port 1(veth4342849) entered disabled state
> [444323.588446] docker0: port 1(veth4342849) entered disabled state
> [444323.588964] device veth4342849 left promiscuous mode
> [444323.588969] docker0: port 1(veth4342849) entered disabled state
> [444391.229246] aufs au_opts_verify:1570:dockerd[18312]: dirperm1 breaks the protection by the permission bits on the lower branch
> [444391.292185] aufs au_opts_verify:1570:dockerd[18312]: dirperm1 breaks the protection by the permission bits on the lower branch
> [444412.550233] aufs au_opts_verify:1570:dockerd[18312]: dirperm1 breaks the protection by the permission bits on the lower branch
> [444412.565982] device veth0edae40 entered promiscuous mode
> [444412.566028] IPv6: ADDRCONF(NETDEV_UP): veth0edae40: link is not ready
> [444412.566031] docker0: port 1(veth0edae40) entered forwarding state
> [444412.566037] docker0: port 1(veth0edae40) entered forwarding state
> [444412.566535] docker0: port 1(veth0edae40) entered disabled state
> [444412.793941] docker0: port 1(veth0edae40) entered disabled state
> [444412.794493] device veth0edae40 left promiscuous mode
> [444412.794499] docker0: port 1(veth0edae40) entered disabled state
> [444671.682122] aufs au_opts_verify:1570:dockerd[28116]: dirperm1 breaks the protection by the permission bits on the lower branch
> [444671.705752] aufs au_opts_verify:1570:dockerd[28116]: dirperm1 breaks the protection by the permission bits on the lower branch
> [444671.726593] device veth288f48f entered promiscuous mode
> [444671.726640] IPv6: ADDRCONF(NETDEV_UP): veth288f48f: link is not ready
> [444671.726643] docker0: port 1(veth288f48f) entered forwarding state
> [444671.726647] docker0: port 1(veth288f48f) entered forwarding state
> [444671.727212] docker0: port 1(veth288f48f) entered disabled state
> [444672.887793] IPv6: ADDRCONF(NETDEV_CHANGE): veth288f48f: link becomes ready
> [444672.887812] docker0: port 1(veth288f48f) entered forwarding state
> [444672.887819] docker0: port 1(veth288f48f) entered forwarding state
> [444687.932588] docker0: port 1(veth288f48f) entered forwarding state
> [444691.646841] kodi.bin[28949]: segfault at 7a8 ip 00007fab82d63277 sp 00007fab6c25b750 error 4 in kodi.bin[7fab825e7000+201c000]
> [444710.289167] kodi.bin[29074]: segfault at 7a8 ip 00007f72682ec277 sp 00007f72517e4750 error 4 in kodi.bin[7f7267b70000+201c000]
> [444729.011984] kodi.bin[29199]: segfault at 7a8 ip 00007f9616d90277 sp 00007f9600288750 error 4 in kodi.bin[7f9616614000+201c000]
> [444747.737515] kodi.bin[29332]: segfault at 7a8 ip 00007f9da34ef277 sp 00007f9d8c9e7750 error 4 in kodi.bin[7f9da2d73000+201c000]

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by sparklyballs** [comment]
there is an ongoing issue with kodi headless jarvis branch and something related to possible corrupt addon mirrors (tbh nobody actually really knows exactly what it is) that affects all Jarvis headless containers, not just ours.

from [this post](http://lime-technology.com/forum/index.php?topic=42439.msg493378#msg493378)  onwards on the unraid forum talks about the issue and there are some fixes there.

**Comment by simkin** [comment]
Thanks! will start reading

**Comment by Xmister** [comment]
For anyone else ending up here, an even easier solution is just a docker argument:
`--add-host mirrors.kodi.tv:127.0.0.1`
