### ISSUE TITLE
Streaming to Yatse app on android, not working

### ISSUE THREAD

**Issue by snow3461** [linuxserver/docker-kodi-headless#47]
Docker container running on OpenMediaVault.
Sources are nfs share on same host (sources.xml added).

Anybody having a working Yatse+Kodi-headless working?

Can provide logs, but dont know what to provide.

**Comment by sparklyballs** [comment]
it's not designed for that and not something we support

**Comment by snow3461** [comment]
Ok, didnt know that.
I saw your repo "kodi-headless-yatse" and thought this could work. 
Many thanks.
