### ISSUE TITLE
Base image alpine instead of xenial ?

### ISSUE THREAD

**Issue by muhahacz** [linuxserver/docker-kodi-headless#55]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Hello, 
why is this image based on xenial? Better support of HWaccelearation, or what? 
At least change README.md
`It is based on alpine linux with s6 overlay, for shell access whilst the container is running do docker exec -it kodi-headless /bin/bash.`
Thanks

**Comment by sparklyballs** [comment]
it was based upon alpine linux for a while but kodi requires some specific patches for alpine to be able to compile and waiting for alpine to update their kodi version to get the latest patches was getting a little silly so we moved back to xenial

**Comment by muhahacz** [comment]
@sparklyballs Today 17.3-r2
https://pkgs.alpinelinux.org/package/edge/community/x86/kodi

**Comment by sparklyballs** [comment]
that just validates the decision to use xenial in place of alpine.

26 days for release of 17.3 on alpine , which is the quickest i've known them release a version yet, but it's still a month......
