### ISSUE TITLE
Webserver not starting

### ISSUE THREAD

**Issue by arette** [linuxserver/docker-kodi-headless#56]
Running this container on latest Synology DSM.  Webserver is not starting on port 8282 anymore after updating to Krypton.  I have copied the .kodi directory from an existing OpenELEC Krypton install where guisettings.xml contains below and the webserver works properly (looks like krypton default is chorus2 interface, which looks slick but is definitely new...)
`
<services>
        <webserver default="true">true</webserver>
        <webserverpassword>XXXXX</webserverpassword>
        <webserverport>8282</webserverport>
        <webserverusername default="true">kodi</webserverusername>
        <webskin default="true">webinterface.default</webskin>
        <zeroconf default="true">true</zeroconf>
</services>
`

When I launch the container, the web interface page fails to load and the <webserver> setting in guisettings.xml gets automatically set from true to false.  This will continue to happen on each boot.  Any one else having luck with webserver on latest container?

**Comment by Gomez** [comment]
@arette You solved this? I have the same here:
https://github.com/Celedhrim/docker-kodi-server/issues/9
Any help would be really cool!
