### ISSUE TITLE
kodi krypton - 17.4

### ISSUE THREAD

**Issue by thezoggy** [linuxserver/docker-kodi-headless#57]
17.4rc1 came out a week ago: https://kodi.tv/article/kodi-v174-rc1-just-bunch-fixes

also have you tried doing any  "Leia" builds yet?

**Comment by sparklyballs** [comment]
not a one of those fixes seem at all relevant to a headless installation, and don't usually look at anything until a release.

haven't even begun to think about looking at leia yet.

**Comment by thezoggy** [comment]
one of the reasons im curious to try 17.4rc1 on headless is because of: https://github.com/xbmc/xbmc/pull/12111

as i really want to get away from smb v1
