### ISSUE TITLE
kodi-headless not delivering art via UPnP

### ISSUE THREAD

**Issue by greyslater** [linuxserver/docker-kodi-headless#6]
Hey there,

I've had the problem that kodi is not delivering **art = poster / thumbnail image** to my upnp clients. It's independent from which version i choose 14 / 15 / 16.
Everything else is running fine, upnp-http get for the video file is good but for the images the clients gets a **`404 Not Found`** whereas on the webservice all pictures are displayed correctly.

What my log says with debug logging enabled:

````
00:33:04 T:140420440901376    INFO: Platinum [platinum.core.http.server]: PLT_HttpServer::SetupResponse GET request from 172.27.1.103:55037 for "http://172.27.2.12:1645/%25/1C90D66AAA7F172E0134A3550B032A00/1G1BZGMoca2JwV9L2KA5NYJwHvR.jpg"
                                            GET /%25/1C90D66AAA7F172E0134A3550B032A00/1G1BZGMoca2JwV9L2KA5NYJwHvR.jpg HTTP/1.1
                                            User-Agent: BubbleUPnP UPnP/1.1
                                            Host: 172.27.2.12:1645
                                            Connection: Keep-Alive
                                            Accept-Encoding: gzip
00:33:04 T:140420440901376    INFO: Platinum [platinum.media.server.file.delegate]: PLT_FileMediaServerDelegate::ProcessFileRequest:
                                            GET /%25/1C90D66AAA7F172E0134A3550B032A00/1G1BZGMoca2JwV9L2KA5NYJwHvR.jpg HTTP/1.1
                                            User-Agent: BubbleUPnP UPnP/1.1
                                            Host: 172.27.2.12:1645
                                            Connection: Keep-Alive
                                            Accept-Encoding: gzip
00:33:04 T:140420440901376   DEBUG: Received request to serve '1C90D66AAA7F172E0134A3550B032A00/1G1BZGMoca2JwV9L2KA5NYJwHvR.jpg' = 'image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f1G1BZGMoca2JwV9L2KA5NYJwHvR.jpg/'
00:33:04 T:140420440901376 WARNING: Platinum [platinum.media.server.file.delegate]: NPT_CHECK failed, result=-20005 (NPT_ERROR_NO_SUCH_ITEM) [(ServeFile(request, context, response, NPT_FilePath::Create(m_FileRoot, file_path)))]
00:33:04 T:140420440901376    INFO: Platinum [platinum.core.http.servertask]: PLT_HttpServerSocketTask::Write
                                            HTTP/1.1 404 Not Found
                                            Content-Disposition: inline; filename=""
                                            Date: Sat, 12 Mar 2016 23:33:04 GMT
                                            Content-Length: 132
                                            Content-Type: text/html
                                            Server: UPnP/1.0 DLNADOC/1.50 Kodi
````

I would appreciate any insight into this.

I love to use docker-headless kodi mainly as upnp-server. Not for kodi-upnp-clients but everything else so i don't need to have my main openELEC Box running for this all the time.
It does a realy good job - great work guys
Thanks in advance!

**Comment by sparklyballs** [comment]
the :// part of the address is converted to % codes and is not being understood.

don't know how to solve that.

**Comment by greyslater** [comment]
it's not directly an issue with the % codes because the video file itself can be played also with a identical URL:

http://172.27.2.12:1645/%25/F2D41D73EB4B656029CB2D4F2C90BEB9/qrc-snatch.mkv

although the images URL is different because of the images are not stored together with the video file
there must be a module for caching the images (in the Thumbnails folder) because in the VideoDatabase there is only the external URL for the images (in my case themovieDB)
but the UPnP Server doesn't know where to grab the images from
