### ISSUE TITLE
update package

### ISSUE THREAD

**Issue by thezoggy** [linuxserver/docker-kodi-headless#62]
can we add vim or less to the docker? would make it much easier to search in logs/edit a file to test something.

also side question,
in your kodi.log do you see "smbc errno NT_STATUS_OBJECT_NAME_NOT_FOUND" entries?

**Comment by thelamer** [comment]
I do not speak for the team, but adding debugging tools to a container is a big no no in the docker world. The container exists to do one thing, run the application inside of it. 

If debugging tools are needed from time to time, install them:
```
apt-get update && apt-get install vim less -y
```
The error you are getting is a samba error double check the permissions on the files in your shared folder, and reach out to the Kodi team with the error and logs:

https://forum.kodi.tv/forumdisplay.php?fid=111

**Comment by thezoggy** [comment]
you definition of debugging tools is very lose. anyways the error only shows up in this docker, not in any other kodi instance (on shield/firetv/etc) in my house. so it looks like something specific to the hacks/build/setup of this. i would assume a byproduct of the version of samba used..

**Comment by thelamer** [comment]
The only thing installed on the container is the library that the binary needs to function "libsmbclient". 

This is the most up to date version in Ubuntu Xenial there are no hacks or weird setups, this is the same .so loaded on a stock Ubuntu OS.

Samba is a weird one when it comes to permissions, keep in mind these containers use the S6 overlay and run as the UID/GID you passed to it. So when they are accessing a Samba share they look like that UID named abc.

**Comment by thezoggy** [comment]
the uid/gid is the default noboddy user for unraid, which works fine for ever now. 

a snippet of docker logs, can see that its trying to see if there is a `.nomedia` to see if it should ignore the file..  but oddly its looking for the .nomedia file in the episode file as if it was a directory.
which makes me thing something with the headless patch...  
```
smbc errno NT_STATUS_OBJECT_PATH_NOT_FOUND -> 2
smbc_stat(smb://husky/TV/TV/xxxxxxxxxxxxxxxxx.mkv/.nomedia)
SMBC_getatr: sending qpathinfo
num_setup=1, max_setup=0, param_total=196, this_param=196, max_param=2, data_total=0, this_data=0, max_data=65535, param_offset=68, param_pad=0, param_disp=0, data_offset=264, data_pad=0, data_disp=0
num_setup=1, max_setup=0, param_total=196, this_param=196, max_param=2, data_total=0, this_data=0, max_data=65535, param_offset=68, param_pad=0, param_disp=0, data_offset=264, data_pad=0, data_disp=0
map_errno_from_nt_status: 32 bit codes: code=c000003a
smbc errno NT_STATUS_OBJECT_PATH_NOT_FOUND -> 2
smbc_stat(smb://husky/TV/TV/xxxxxxxxxxxxxxxxx.mkv/.nomedia)
SMBC_getatr: sending qpathinfo
num_setup=1, max_setup=0, param_total=172, this_param=172, max_param=2, data_total=0, this_data=0, max_data=65535, param_offset=68, param_pad=0, param_disp=0, data_offset=240, data_pad=0, data_disp=0
num_setup=1, max_setup=0, param_total=172, this_param=172, max_param=2, data_total=0, this_data=0, max_data=65535, param_offset=68, param_pad=0, param_disp=0, data_offset=240, data_pad=0, data_disp=0
map_errno_from_nt_status: 32 bit codes: code=c000003a
smbc errno NT_STATUS_OBJECT_PATH_NOT_FOUND -> 2
smbc_stat(smb://husky/TV/TV/xxxxxxxxxxxxxxxxx.mkv/.nomedia)
SMBC_getatr: sending qpathinfo
```
