### ISSUE TITLE
Media location?

### ISSUE THREAD

**Issue by cmullins83** [linuxserver/docker-kodi-headless#65]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Ubuntu 16.04
docker create --name=kodi --restart=unless-stopped -v /Docker/Kodi:/config/.kodi -e PGID=1000 -e PUID=1000 -e TZ=America/Chicago -v /media/Media/Media:/media -p 8080:8080 -p 9777:9777/udp linuxserver/kodi-headless

There is not a clear way to add media. I can't seem to find how to do it.

**Comment by thezoggy** [comment]
https://github.com/linuxserver/docker-kodi-headless#setting-up-the-application

**Comment by cmullins83** [comment]
Which tells me how to set up the database...

**Comment by cmullins83** [comment]
Kind of missing the point "instructions unclear"

**Comment by j0nnymoe** [comment]
you have to add/scan the media via a kodi client. kodi-headless is designed to work with a shared database setup and take notification calls to scan/update the database.

**Comment by thezoggy** [comment]
you setup your advancedsettings and sources file.. 
then you place them in your proper locaton on the docker, which kodi uses on startup and will update said locations...
