### ISSUE TITLE
Activating `Unknown sources` kills container

### ISSUE THREAD

**Issue by alexanderadam** [linuxserver/docker-kodi-headless#66]
Every time I try to activate

`Settings > System > Add-ons > Unknown sources`

it kills the container. Anything I could have missed?

```
ERROR: Exception caught on main loop. Exiting
./run: line 2:  6948 Segmentation fault      (core dumped) s6-setuidgid abc /usr/lib/kodi/kodi.bin --headless

```

**Comment by sparklyballs** [comment]
don't install addons to this container

**Comment by alexanderadam** [comment]
Thank you for your fast response.

Okay, in that case it might be useful that addons aren't supported in this container.
Have a nice week!
