### ISSUE TITLE
initial password is worng.

### ISSUE THREAD

**Issue by dimaj** [linuxserver/docker-kodi-headless#72]
In the readme, it is said that initial credentials for the web interface is: `kodi`/`kodi`. In reality it is `xbmc`/`xbmc`

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by sparklyballs** [comment]
new pull with no existing appdata and the webui password is kodi/kodi

**Comment by dimaj** [comment]
You're right... https://github.com/linuxserver/docker-kodi-headless/blob/master/root/defaults/advancedsettings.xml#L39 . my bad
