### ISSUE TITLE
18.0 -- question

### ISSUE THREAD

**Issue by thezoggy** [linuxserver/docker-kodi-headless#75]
@sparklyballs do you plan on doing a release for any of the alpha/betas ? or just waiting until final/rc ?

**Comment by sparklyballs** [comment]
it's alpha which means not touching it with a barge pole

**Comment by thezoggy** [comment]
so to circle back, when do you plan to do a v18 release? ~alpha?~ beta? rc? final?

**Comment by gurabli** [comment]
Plus one on this, as Kodi v18 is in beta 4 stage, and we are probably very close to final/RC. This could be certainly considered stable, at least on newer platforms. I use CoreELEC, and many of us use v18 since long time, for Netflix, etc support. I hope the patches will be available soon. Thanks
