### ISSUE TITLE
Leia Beta 2 Availability?

### ISSUE THREAD

**Issue by bdpna** [linuxserver/docker-kodi-headless#78]
Not so much an issue, just wondering if this docker will have a Leia option now that we hit beta which has proven very stable for past releases.  

I am a MySQL user and as a result need to sync my Kodi installs across the house on the same platform to use the database.  As I'm migrating all my systems to Leia, I'd love to also move my headless install (which I use to handle DB updates) as well.

Thanks for considering and for the work you do.

**Comment by sparklyballs** [comment]
nothing works yet, patch wise or the gbm version of kodi.
