### ISSUE TITLE
PVR support

### ISSUE THREAD

**Issue by rubdos** [linuxserver/docker-kodi-headless#82]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
##  Thanks, team linuxserver.io

My ultimate goal with #81 is to have a headless audio-player, including PVR support (through TvHeadend). I suppose that the image will grow quite a bit in complexity if I would add PVR support. So my question is: would you accept a patch that includes the PVR addons?

Side question: I wonder how the configuration of the addon will be. Is that automagically included in the webinterface/#settings/addons ?

**Comment by sparklyballs** [comment]
This goes way beyond what the container is purposed for.  If you want to fork and make your own changes to facilitate this, have at it, it’s not something I would envisage being supported by us.

**Comment by sparklyballs** [comment]
This goes way beyond what the container is purposed for.  If you want to fork and make your own changes to facilitate this, have at it, it’s not something I would envisage being supported by us.
