### ISSUE TITLE
Party-mode segfault

### ISSUE THREAD

**Issue by rubdos** [linuxserver/docker-kodi-headless#84]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
Any attempt to start party mode crashes with SIGSEG:

    ./run: line 2:  2508 Segmentation fault      (core dumped) s6-setuidgid abc /usr/lib/kodi/kodi.bin --headless

Please inform if you need any more pointers for debugging, but I think reproduction is:

1. Add a few albums to library
2. Start party-mode (this is including my ALSA patch #81, but I don't think that matters)

I think it's because Kodi tries to draw the "starting party mix" dialog, and cannot do that on headless?

**Comment by j0nnymoe** [comment]
This headless container was only ever designed to be used for update notifications in a shared sql environment unfortunately.

**Comment by rubdos** [comment]
> This headless container was only ever designed to be used for update notifications in a shared sql environment unfortunately.

Yeh, I get that. Doesn't mean we couldn't extend it to do more stuff. I am willing to contribute time and code here if someone could give me a few pointers. Note that I *can* play pvr.hts radio and full albums using the simple patches in #81 and #82, so I don't think it'll be a very large thing to fix.

I wonder whether it's a mainline thing, or whether a patch should land here in `/patches/Krypton` though?

**Comment by j0nnymoe** [comment]
To be honest, I'm not a dev but if I remember correctly the patch was pretty hacky as naturally Kodi isn't supposed to run like this. 

Personally I gave up on running this a while back and switched to emby as a backend.

**Comment by sparklyballs** [comment]
the image is not designed for this.. 

so basically it crashing doing something it shouldn't be doesn't really constitute an issue.

**Comment by rubdos** [comment]
Well, I can still say that it's solved in the Leia version, where you use a virtual display instead of the headless patch... :'-)
