### ISSUE TITLE
kodi - rar support is disabled

### ISSUE THREAD

**Issue by thezoggy** [linuxserver/docker-kodi-headless#9]
noticed that kodi is not built with rar, (i happen to have some subs still in their rars and saw errors about unable to view the files when it was doing a library update)

`18:33:01 T:47995934799616 WARNING: Create - Compiled without non-free, rar support is disabled`

**Comment by sparklyballs** [comment]
i'm not sure what the issue is here, you can't see subs on a headless instance....

**Comment by thezoggy** [comment]
kodi has the ability to see files inside rarset... which could be media files/subs/whatever. i just was noting that i happen to have a few subs that were rarsets which is how i discovered this due to the warning. if you dont want to compile with rar thats fine, just something to note where this kodi instance may not see all the files another one would.
