### ISSUE TITLE
rar file support

### ISSUE THREAD

**Issue by Gomez** [linuxserver/docker-kodi-headless#91]
With kodi v18 the rar support was moved (out of the core) into a addon (https://github.com/xbmc/vfs.rar).

It would be great to add this addon to the dockerfile an fix the regression. Otherwise movies/music in rar files wont be removed / not added to library.

**Comment by Gomez** [comment]
Maybe this addon is the better choice: https://github.com/xbmc/vfs.libarchive

**Comment by sparklyballs** [comment]
i've built it locally with both addons (belt and braces, etc) 

you can test by pulling 

sparklyballs/kodi-testit

docker image. 

you have to enable the addons in the addons section of the webui. 

if it works i will push the changes to this repo and you can switch back to the normal image. i'm busy trying to build the armhf version of this image and unable to test this, hence the push to my personal hub repository.

**Comment by Gomez** [comment]
Thanks! I pulled the new and activated the plugin. We monitor the result the next days...
