### ISSUE TITLE
Question: Library Update/Clean Schedule

### ISSUE THREAD

**Issue by raupie** [linuxserver/docker-kodi-headless#99]
Does this container have the ability to schedule library updates/clean? Such as a cron schedule extra?

The documentation is very thin so I was expecting this feature to be somewhere obvious. Is the expectation you update/clean manually from the shell or via the web console of kodi?

Thanks.

**Comment by ciarancoffey** [comment]
You've probably found this out, but for someone googling I run this via a cron:
```$ cat ./kodi_scan.sh 
#!/usr/bin/env bash

CURL_OUTPUT=$(/usr/bin/curl --data-binary '{ "jsonrpc": "2.0", "method": "VideoLibrary.Scan", "id": "cronupdate"}' -H 'content-type: application/json;' http://kodi:kodi@10.2.2.200:8000/jsonrpc --silent --max-time 20 )
RESPONSE=$(echo $CURL_OUTPUT| jq '.result')
if [ -z "$CURL_OUTPUT" ]; then
  echo "Failure curling to kodi"
  exit 10
fi
if [ "$RESPONSE" = '"OK"' ]; then
  exit 0 
else
  echo "Failure with Kodi backend"
  echo $(echo $CURL_OUTPUT | jq '.error.message')
  exit 11
fi
```

**Comment by raupie** [comment]
That's awesome, thank you for sharing. 

Yup, figured cron is the way to do it from the NAS or wherever. 

Would be nice if this feature was added to keep it all together.

I was using the milaq/kodi-headless image which had the built in cron feature which was nice.
